Mendel/urlroutes/account/routes.py
# ROUTING PAGE FOR THE ACCOUNT ANALYSIS TAB, MANAGER IS REQUIRED SELECT A SALES REP AND ACCOUNTS UNDER LATTER TO VIEW KPIS
# SALES REP IS REQUIRED ONLY TO SELECT THE ACCOUNTS FROM DROP DOWN

#IMPORTING THE REQUIRED LIBRARIES
import math
import pandas as pd
from Mendel import db
from sqlalchemy import text
from Mendel.models import User
from flask_login import  current_user    
from flask import render_template, request, flash, redirect, url_for,jsonify, Blueprint
import Mendel.mlmodel.hcp_clustering_segmentation as clt
import Mendel.mlmodel.hcp_propensity_modeling as mdl





#CREATING THE BLUE PRINT VARIABLE FOR THE ACCOUNT FOR ROUNTING 
account = Blueprint('account', __name__)





#LOADING THE REQUIRED FILES FOR SHOWING THE ANALYSIS
#FOR NOW ML MODEL IS NOT INTEGRATED THEREFORE KPIS SHOWN FROM FILES 
timeseries = pd.read_csv("Mendel/static/data/timeseries.csv")
propensity_scaled = pd.DataFrame(mdl.propensity_rescale)
master_km = pd.DataFrame(clt.master_km)


propensity_p=pd.DataFrame(mdl.propensity)
propensity = propensity_p.merge(master_km[['account_name','cluster_id']],on='account_name')
#propensity = pd.read_csv("Mendel/static/data/propensity.csv")

propensity['cluster_id']=propensity['cluster_id'].astype(str)
propensity['cluster_id'].replace('0','A',inplace=True)
propensity['cluster_id'].replace('1','B',inplace=True)
propensity['cluster_id'].replace('2','C',inplace=True)
propensity['cluster_id'].replace('3','D',inplace=True)






#ROUTE FOR ACCOUNT ANALYSIS TAB
@account.route("/accountanalysis")
def accountanalysis():
    #user authetication
    if current_user.is_authenticated==False:
        flash('User not logged in', 'info')
        return redirect(url_for('main.login'))
    
    #if the logged in user is a sales rep then a dropdown of mapped sales reps is also displayed
    #retrieving reps mapped to manager
    replist=[]
    if(current_user.user_type=='admin'):
        reps=db.session.query(User).from_statement(text("SELECT * FROM user where manager_id="+str(current_user.id))).all()
        for rep in reps:
            replist.append(rep.username)
    
    #retrieving account names from file
    accounts=propensity['account_name']
    
    #sending the details to 'accountanalysis.html' template
    return render_template('accountanalysis.html',accounts=accounts,title='Account Analysis',reps=replist)







#FUNCTIONALTY TO FILTER DATAFRAME WITH SELECTED ACCOUNTS AND USER
@account.route("/accountanalysis_filter", methods=['GET', 'POST'])
def accountanalysis_filter():
    try:
        #date filters are currently not applied
        Initial_date = request.args.get('Initial_date', default="", type=str)
        Final_date = request.args.get('Final_date', default="", type=str)
        #dt = parse(Initial_date)
        
        #retrieving the selected account name
        Account_Names = request.args.get('Account_Names', default="", type=str)
        
        
        #creating a global variables with filtered data
        global Filtered_account
        global Scaled_account
        Filtered_account = propensity[propensity['account_name']==Account_Names]
        Scaled_account = propensity_scaled[propensity_scaled['account_name']==Account_Names]
        
        #data type convertion for UI rendering
        account_relation=float(Filtered_account['account_relation'])
        injection_potential=float(Filtered_account['injection_potential'])
        pal=float(Filtered_account['pal'])
        competitive_situation=float(Filtered_account['competitive_situation'])
        clinical_mindset=float(Filtered_account['clinical_mindset'])
        value_perception=float(Filtered_account['value_perception'])
        segment=(str(Filtered_account['cluster_id'])).split()
        
        #color codes for the heat map generation
        colors=['#cc0000','#ff3333','#ff8080','#d9f2e4','#9fdfbc','#66cc94','#40bf79','#39ac6d','#2d8655','#20603d']
        
        #variables with color codes for UI rendering        
        account_relation_c=colors[math.floor(float(Scaled_account['account_relation']))-1]
        injection_potential_c=colors[math.floor(float(Scaled_account['injection_potential']))-1]
        pal_c=colors[math.floor(float(Scaled_account['pal']))-1]
        competitive_situation_c=colors[math.floor(float(Scaled_account['competitive_situation']))-1]
        clinical_mindset_c=colors[math.floor(float(Scaled_account['clinical_mindset']))-1]
        value_perception_c=colors[math.floor(float(Scaled_account['value_perception']))-1]
        
        #sending the variables to UI
        return jsonify(account_relation=round(account_relation,2),injection_potential=round(injection_potential,2),pal=round(pal,2),competitive_situation=round(competitive_situation,2),clinical_mindset=round(clinical_mindset,2),value_perception=round(value_perception,2),account_relation_c=account_relation_c,injection_potential_c=injection_potential_c,pal_c=pal_c,competitive_situation_c=competitive_situation_c,clinical_mindset_c=clinical_mindset_c,value_perception_c=value_perception_c,segment=segment[1])
    except Exception as e:
        return str(e)   







    
#FUNCTIONALTY TO SEND SALES COMPARISON DATA TO  D3.JS FUNCTION TO CREATE RADIAL BAR CHART 
@account.route('/get_h_barchart_data')
def get_h_barchart_data():
    
    #data type conversion and computation variables creation
    actual_sales=int(Filtered_account['actual_sales'])
    target_sales=int(Filtered_account['target_sales'])
    patients_treated_with_selling_drug=int(Filtered_account['patients_treated_with_selling_drug'])
    patients_treated_with_competitive_drug=int(Filtered_account['patients_treated_with_competitive_drug'])
    act_color=None
    comp_color=None
    
    #competitor analysis score generation
    if patients_treated_with_competitive_drug>0:
            compdiv=patients_treated_with_selling_drug/patients_treated_with_competitive_drug
    else:
        compdiv=1

    #competitor analysis bar color coding
    if compdiv>0.2:
        comp_color='#ffff1a'
    else:
        comp_color='#ff471a'      
    
    #sales comparsion color coding
    if actual_sales<target_sales:
        act_color='#ff471a'
    else:
        act_color='#39ac6d'
    
    #Creating the json object with the data for 'd3.js' functions
    hbarData = []
    eachData = {}
    eachData['group'] = 'Sales'
    eachData['category'] = 'Target Sales'
    eachData['measure'] =  target_sales
    eachData['color'] = '#346DC3'
    hbarData.append(eachData)
    
    eachData = {}
    eachData['group'] = 'Sales'
    eachData['category'] = 'Actual Sales'
    eachData['measure'] =  actual_sales
    eachData['color'] = act_color
    hbarData.append(eachData)
    
    eachData = {}
    eachData['group'] = 'Comp_Analysis'
    eachData['category'] = 'Competitor'
    eachData['measure'] =  patients_treated_with_competitive_drug
    eachData['color'] = '#4d4dff'
    hbarData.append(eachData)
    
    eachData = {}
    eachData['group'] = 'Comp_Analysis'
    eachData['category'] = 'Own'
    eachData['measure'] =  patients_treated_with_selling_drug
    eachData['color'] = comp_color
    hbarData.append(eachData)
    
    #sending the json object
    return jsonify(hbarData)    






#FUNCTIONALTY TO SEND SALES MARKET SHARE DATA TO  D3.JS FUNCTION TO GAUGE CHART 
@account.route('/get_gauge_chart_data')
def get_gauge_chart_data():

    #data type conversion and computation variables creation
    patients_treated_with_selling_drug=int(Filtered_account['patients_treated_with_selling_drug'])
    patients_treated_with_competitive_drug=int(Filtered_account['patients_treated_with_competitive_drug'])
    
    #market share calculation
    if patients_treated_with_competitive_drug>0:
            compdiv=(patients_treated_with_selling_drug/patients_treated_with_competitive_drug)*100
    else:
        compdiv=100

    #creating the json data 
    hbarData = []
    eachData = {}
    eachData['measure'] =  round(compdiv,1)
    hbarData.append(eachData)
  
    #sending the json data to gauge chart d3.js
    return jsonify(hbarData)   






#FUNCTIONALTY TO SEND TIME SERIES SALES DATA TO CREATE SALES LINE CHART
@account.route('/get_timeseries_data')
def get_timeseries_data():
    
    #json object with time series sales data
    hbarData=[]
    for index, row in timeseries.iterrows():
        eachData = {}
        eachData['date'] = row['date']
        eachData['actual_sales'] =  row['actual_sales']
        eachData['target_sales'] =  row['target_sales']
        hbarData.append(eachData)

    #sending the json object to line chart d3.js
    return jsonify(hbarData)    



    

Mendel/urlroutes/ranking/routes.py
#TARGET RANKING PAGE DISPLAYS THE SCATTER PLOT OF CLUSTER ANALYSIS OF THE ACCOUNTS UNDER A SALES REPRESENTATIVE 


#IMPORT ALL THE REQUIRED LIBRARIES
import pandas as pd
from Mendel import db
from sqlalchemy import text
from Mendel.models import User
from flask_login import  current_user    
from flask import render_template,  flash, redirect, url_for,jsonify, Blueprint
import Mendel.mlmodel.hcp_clustering_segmentation as clt
import Mendel.mlmodel.hcp_propensity_modeling as mdl



#CREATING THE BLUE PRINT VARIABLE FOR THE RANKING FOR ROUNTING 
ranking = Blueprint('ranking', __name__)





#READING THE REQUIRED FILES, CURRENTLY THE INTERGRATION IS NOT COMPLETE THEREFORE DISPLAYING THE KPIS USING FILES

master_km = pd.DataFrame(clt.master_km)
propensity_p=pd.DataFrame(mdl.propensity)
propensity = propensity_p.merge(master_km[['account_name','cluster_id']],on='account_name')


#propensity = pd.read_csv("Mendel/static/data/propensity.csv")
propensity['cluster_id']=propensity['cluster_id'].astype(str)
propensity['cluster_id'].replace('0','A',inplace=True)
propensity['cluster_id'].replace('1','B',inplace=True)
propensity['cluster_id'].replace('2','C',inplace=True)
propensity['cluster_id'].replace('3','D',inplace=True)






#ROUTE FOR TARGET RANKING HTML
@ranking.route("/targetranking")
def targetranking():
    #user authentication
    if current_user.is_authenticated==False:
        flash('User not logged in', 'info')
        return redirect(url_for('main.login'))
    
    #if the logged in user is manager, then loading the list of mapped sales reps
    replist=[]
    if(current_user.user_type=='admin'):
        reps=db.session.query(User).from_statement(text("SELECT * FROM user where manager_id="+str(current_user.id))).all()
        for rep in reps:
            replist.append(rep.username)
    
    #loading the html template as GET request 
    return render_template('targetranking.html',title='Target Ranking',reps=replist)




#ROUTE FOR CREATING JSON DATA FOR THE SCATTER PLOT
@ranking.route("/scatterplot_data")
def scatterplot_data():
    #multiline comment for scatterplot data using database
    '''
    accounts=db.session.query(Account).from_statement(text("SELECT * FROM account where user_id="+str(current_user.id))).all()
    jsonData = []
    for account in accounts:
        potvalue=0
        counter=0
        prob_score=0
        selling_drug=0
        competitor_drug=0
        account_vars=db.session.query(Account_Var).from_statement(text("SELECT * FROM account_var where npi_id="+str(account.id))).all()
        for account_var in account_vars:
            counter=counter+1
           potvalue=potvalue+account_var.Potential_Value
            prob_score=prob_score+account_var.Prob_Score
            selling_drug=selling_drug+account_var.Selling_Drug
            competitor_drug=competitor_drug+account_var.Competitor_Drug
        pscore=prob_score/counter
        m_share=(selling_drug/competitor_drug)*100    
        eachData = {}
        eachData['group'] = 'Account'
        eachData['name'] = account.Account_Name
        eachData['Probability_Score'] =  pscore
        eachData['Potential_Value'] = potvalue
        eachData['Market_Share'] = m_share
        jsonData.append(eachData)
    '''
    
    #converting data frame to json
    jsonData = []
    
    #loading dataframe line by line to dataframe
    for index,row in propensity.iterrows():
        if row['patients_treated_with_competitive_drug']>0:
            m_share=((row['patients_treated_with_selling_drug']/row['patients_treated_with_competitive_drug'])*100)
        else:
            m_share=100
        eachData = {}
        eachData['group'] = 'Account'
        eachData['name'] = row['account_name']
        eachData['Probability_Score'] =  round(m_share,2)
        eachData['Potential_Value'] = row['total_potential_value']
        eachData['Market_Share'] = round(m_share,2)
        eachData['Segment'] = 'Segment '+row['cluster_id']
        jsonData.append(eachData)
    
    #sending the data to the scatter plot d3.js
    return jsonify(jsonData)   



		

Mendel/templates/accountanalysis.html
{% extends "layout.html" %}
{% block content %}
<html>
<head>
<!--<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">-->
<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/bootstrap.min.3.3.6.css')}}">

<!--<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css">-->
<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/bootstrap-datetimepicker.min.css')}}">

<!--<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>-->
<script src="{{ url_for('static', filename='js/jquery-3.3.1.slim.min.js') }}"></script>

<!--<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js"></script>-->


<!--<script src="https://d3js.org/d3.v4.min.js"></script>-->
<script src="{{ url_for('static', filename='js/d3.v4.min.js') }}"></script>

<!--<script src="https://d3js.org/queue.v1.min.js"></script>-->
<script src="{{ url_for('static', filename='js/queue.v1.min.js') }}"></script>

<!--<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script> -->
<script type="text/javascript" src="{{ url_for('static', filename='js/jquery.js') }}"></script> 

<!--<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/2.14.1/moment.min.js"></script>-->
<script type="text/javascript" src="{{ url_for('static', filename='js/moment.min.js') }}"></script>

<!--<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>-->
<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.3.3.6.js') }}"></script>

<!--<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>-->
<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap-datetimepicker.min.js') }}"></script>
<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/button.css')}}">
<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/accountanalysis.css')}}">	
<script type="text/javascript">
    $(function () {
        $('#datetimepicker6').datetimepicker();
        $('#datetimepicker7').datetimepicker({
            useCurrent: false //Important! See issue #1075
			
        });
        $("#datetimepicker6").on("dp.change", function (e) {
            $('#datetimepicker7').data("DateTimePicker").minDate(e.date);
        });
        $("#datetimepicker7").on("dp.change", function (e) {
            $('#datetimepicker6').data("DateTimePicker").maxDate(e.date);
        });
    });
</script>
<script type=text/javascript>
$(function() {
$("#update_button").click(function(){
				$.getJSON('/accountanalysis_filter', {
				  Initial_date: $("#Initial_date").val(),
				  Final_date: $("#Final_date").val(),
				  Account_Names: $("#Account_Names").val(),
}, function(data) {
                    $("#account_relation").text(data.account_relation);
					$("#injection_potential").text(data.injection_potential);
					$("#pal").text(data.pal);
					$("#competitive_situation").text(data.competitive_situation);
					$("#clinical_mindset").text(data.clinical_mindset);
					$("#value_perception").text(data.value_perception);
					$("#segment").text(data.segment);
					
					$("#account_relation_c").css({'background-color':data.account_relation_c});
					$("#injection_potential_c").css({'background-color':data.injection_potential_c});
					$("#pal_c").css({'background-color':data.pal_c});
					$("#competitive_situation_c").css({'background-color':data.competitive_situation_c});
					$("#clinical_mindset_c").css({'background-color':data.clinical_mindset_c});
					$("#value_perception_c").css({'background-color':data.value_perception_c});
					$("#segment_c").css({'background-color':'#39ac6d'});
					
					
					
					
                    hbarchartDataUrl = "{{ url_for('account.get_h_barchart_data') }}";
					linechartDataUrl = "{{ url_for('account.get_timeseries_data') }}";
					gaugechartDataUrl = "{{ url_for('account.get_gauge_chart_data') }}";
				    $("#hbarChart").empty();
					$("#LineChart").empty();
					$("#radialBar").empty();
					$("#gaugeChart").empty();
					
					$("#TargetDefinitionBoxes").css("display", "block");
					$("#chartHeader").css("display", "block");
				    $.getScript("{{ url_for('static', filename='js/hbarChart.js') }}");
					$.getScript("{{ url_for('static', filename='js/AccountLineChart.js') }}");
					$.getScript("{{ url_for('static', filename='js/RadialBarGraph.js') }}");
					$.getScript("{{ url_for('static', filename='js/liquidFillGauge.js') }}");
					$.getScript("{{ url_for('static', filename='js/account_main.js') }}");
				});
				return false;





}); 


});
</script>	
</head>
<body>
  <div class="page-header">
    <h2>HCP/ Account Analysis</h2>      
  </div> 

  {% if current_user.user_type=='admin'%}
<div >
   <div class="row">

    <div class='col-md-2'>
         <select name="Rep_Names" id="Rep_Names" class="btn btn-primary">
			  <option value="">Select Sales Rep</option>  
		      {% for rep in reps	%}
				<option value="{{rep}}">{{rep}}</option>
              {% endfor %}
              <option value="All">All</option>
        </select>
	</div>
 
    <div class='col-md-2'>
       
	       <select name="Account_Names" id="Account_Names" class="btn btn-primary">
			  <option value="">Select HCP/ Account</option>  
		      {% for account in accounts	%}
				<option value="{{account}}">{{account}}</option>
              {% endfor %}
        </select>

	</div>	
	<br>

    <div class='col-md-2'>
        
            <div class='input-group date' id='datetimepicker6'>
                <input type='text' class="form-control" id="Initial_date"/>
                <span class="input-group-addon btn btn-primary">Start Date
                </span>
            </div>
    </div>
    <div class='col-md-2'>
      
            <div class='input-group date' id='datetimepicker7'>
                <input type='text' class="form-control" id="Final_date"/>
                <span class="input-group-addon btn btn-primary">End Date
                </span>
            </div>
      
    </div>
    <div class='col-md-2'>
     <button type="button" id="update_button" class="btn btn-primary">Update</button>
	</div>
   </div>
   </div> 
   {% endif %}
  {% if current_user.user_type=='sales_rep'%}
<div class="container">
   <div class="row">


    <div class='col-md-4'>
       
	       <select name="Account_Names" id="Account_Names" class="btn btn-primary">
			  <option value="">Select Account</option>  
		      {% for account in accounts	%}
				<option value="{{account}}">{{account}}</option>
              {% endfor %}
        </select>

	</div>	
	<br>

    <div class='col-md-3'>
        
            <div class='input-group date' id='datetimepicker6'>
                <input type='text' class="form-control" id="Initial_date"/>
                <span class="input-group-addon btn btn-primary">Start Date
                </span>
            </div>
    </div>
    <div class='col-md-3'>
      
            <div class='input-group date' id='datetimepicker7'>
                <input type='text' class="form-control" id="Final_date"/>
                <span class="input-group-addon btn btn-primary">End Date
                </span>
            </div>
      
    </div>
    <div class='col-md-2'>
     <button type="button" id="update_button" class="btn btn-primary">Update</button>
	</div>
   </div>
   </div> 
   {% endif %}
<br>
<div id="TargetDefinitionBoxes" class='TOuter' style="display: none;">
   <div class='TInner' id="segment_c">
      <h4>Predicted Segment&nbsp;
	  <div class="toolstips"><img src="{{url_for('static',filename='images/info-white.png')}}"height="18" width="18"/>
      <span class="tooltiptexts">Predicted HCP segment</span>
      </div>
	  </h4>	  
	  <span class="spInner" id="segment"></span>
	</div>
    
	<div class='TInner' id="account_relation_c">
      <h4>HCP/ ACC Relationship&nbsp;
	  <div class="toolstips"><img src="{{url_for('static',filename='images/info-white.png')}}"height="18" width="18"/>
      <span class="tooltiptexts">Reps relation with HCPs</span>
      </div>
	  </h4>	 	  
	  <span class="spInner" id="account_relation"></span>
	</div>
	<div class='TInner' id="injection_potential_c">
      <h4>Injection Potential&nbsp;
	  <div class="toolstips"><img src="{{url_for('static',filename='images/info-white.png')}}"height="18" width="18"/>
      <span class="tooltiptexts">Penetrating factor of an HCP</span>
      </div>
	  </h4>	
	  <span class="spInner" id="injection_potential"></span>
	</div>
    <div class='TInner' id="pal_c">
      <h4>Product Adaption Level&nbsp;
	  <div class="toolstips"><img src="{{url_for('static',filename='images/info-white.png')}}"height="18" width="18"/>
      <span class="tooltiptexts">Acceptance of new drug</span>
      </div>
	  </h4>
	  <span class="spInner" id="pal"></span>
	</div>
	<div class='TInner' id="competitive_situation_c">
      <h4>Competitive Situation&nbsp;
	  <div class="toolstips"><img src="{{url_for('static',filename='images/info-white.png')}}"height="18" width="18"/>
      <span class="tooltiptexts">Represent ethical behaviour of an HCP</span>
      </div>
	  </h4>
	  <span class="spInner" id="competitive_situation"></span>
	</div>
    <div class='TInner' id="clinical_mindset_c">
      <h4>Clinical Mindset&nbsp;
	  <div class="toolstips"><img src="{{url_for('static',filename='images/info-white.png')}}"height="18" width="18"/>
      <span class="tooltiptexts">Categorizing HCP or Accounts into High Medium and low  based on preset Market share values </span>
      </div>
	  </h4>
	  <span class="spInner" id="clinical_mindset"></span>
	</div>
    <div class='TInner' id="value_perception_c">
      <h4>Value Perception&nbsp;
	  <div class="toolstips"><img src="{{url_for('static',filename='images/info-white.png')}}"height="18" width="18"/>
      <span class="tooltiptexts">How much value our drug brings to that HCP</span>
      </div>
	  </h4>

	  <span class="spInner" id="value_perception"></span>
	</div>
	
</div>
<br><br>
<div id="chartHeader" style="display: none;">
    <div class='col-md-3'>
	  <h4>Sales Analysis&nbsp;
	  <div class="toolstips"><img src="{{url_for('static',filename='images/info-black.png')}}"height="18" width="18"/>
      <span class="tooltiptexts">Target Sales (Forecasted Sales) vs Actual Sales plot</span>
      </div>
	  </h4>
    </div>	  
	<div class='col-md-3'>
		  <h4>Market Share&nbsp;
	  <div class="toolstips"><img src="{{url_for('static',filename='images/info-black.png')}}"height="18" width="18"/>
      <span class="tooltiptexts">The plot shows the percentage of market controlled by our drug of the HCP</span>
      </div>
	  </h4>
    </div>
	
	
	
	 <div class='col-md-5'>
	  <h4>Quarter to Date&nbsp;
	  <div class="toolstips"><img src="{{url_for('static',filename='images/info-black.png')}}"height="18" width="18"/>
      <span class="tooltiptexts">Target vs Actual Sales at Quarter Level</span>
      </div>
	  </h4>
    </div>
	 
</div> 
<div id="chartRow1">
   <div class='col-md-3' id="hbarChart"></div> 
   <div class='col-md-3' id="gaugeChart"></div>
   <div class='col-md-5' id="LineChart"></div> 
</div>

</html>
{% endblock content %}

Mendel/templates/actionplan.html
{% extends "layout.html" %}


{% block content %}
<html>

<head>

<!--<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">-->
<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/bootstrap.min.3.3.6.css')}}">

<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/actionplan.css')}}">
<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/button.css')}}">	

<!--<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script> -->
<script type="text/javascript" src="{{ url_for('static', filename='js/jquery.js') }}"></script> 


</head>

<body>
 <div class="page-header">
    <h2>Action Plan</h2>      
  </div>
<br><br>
<form action="/goalstrategyurl" method="post">        
<div id="outTable1">
	
      <table id="outputTable1"  border="1">

         <tr>



        <th>Account ID</th>
		<th>Account Name</th> 
		<th>Health Groups</th>
		<th>Market Share in Account</th>
		<th>Percentage of Territory Potential Sales</th>
		<th>Propensity Score</th>
		<th>Predicted Segment</th>
		<th>Next Best Offer</th>
		<th>Goal Strategy</th>
		</tr>
				 {% for account_var in account_vars %}
		       {% for account in accounts %}
		            {% if account.author.username==current_user.username%}
					    {% if account_var.acc.id==account.id %}
		<tr>
			<td>{{ account.Account_ID}}</td>
			<td><a href="\hcp360_2">{{ account.Account_Name}}</a></td>
			<td>{{ account.Health_Groups}}</td>
			<td>{{ Market_Share[loop.index-1]}}%</td>
            <td>{{ Per_Potential_Sales[loop.index-1]}}%</td>
			<td>{{ account_var.Prob_Score}}</td>
			<td>{{ account_var.NBA_insights}}</td>
			
			<td align="left">{% autoescape false %}
                      {{ insights[rand_numbers[loop.index-1]]}}
                 {% endautoescape %}
			</td>
			{% if account_var.Goal_Strategy=='' or account_var.Goal_Strategy==None%}
			<td class="StrategyBox"><input class="StrategyInput" type=text name="StrategyInput_{{loop.index}}" id="StrategyInput_{{loop.index}}" placeholder="Input Goal Strategy" /></td>
		    {% else %}
            <td class="StrategyBox"><input class="StrategyInput" type=text name="StrategyInput_{{loop.index}}" id="StrategyInput_{{loop.index}}" value="{{account_var.Goal_Strategy}}" /></td>
		    {% endif %}
		</tr>
		              {% endif %}
		         {% endif %}
			{% endfor %}	 
		{% endfor %}

	</table>	
</div>
     <br><br>
<div>	 
	 <INPUT class="btn btn-primary" type="submit" id="Save" value="Update" />
</div>
</form>
</body>

</html>

{% endblock content %}